-- MySQL Script generated by MySQL Workbench
-- 10/22/16 18:54:26
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Endereco` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cep` VARCHAR(9) NULL DEFAULT '_____-___',
  `estado` CHAR(2) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `rua` VARCHAR(45) NULL,
  `numero` INT NULL,
  `tipo` CHAR(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Funcionario` (
  `cpf` VARCHAR(15) NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `senha` VARCHAR(20) NOT NULL,
  `dataNascimento` DATE NULL,
  `email` VARCHAR(50) NULL,
  `telefone1` VARCHAR(45) GENERATED ALWAYS AS (),
  `telefone2` VARCHAR(45) NULL,
  `endereco` INT NOT NULL,
  PRIMARY KEY (`cpf`),
  INDEX `fk_Funcionario_Endereco1_idx` (`endereco` ASC),
  CONSTRAINT `fk_Funcionario_Endereco1`
    FOREIGN KEY (`endereco`)
    REFERENCES `mydb`.`Endereco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Contrato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Contrato` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `funcionario` VARCHAR(15) NOT NULL,
  `cargo` CHAR(1) NULL,
  `salario` DECIMAL(10,2) NULL,
  `dataInicio` DATE NULL,
  `dataTermino` DATE NULL,
  PRIMARY KEY (`id`, `funcionario`),
  INDEX `fk_Contrato_Funcionario1_idx` (`funcionario` ASC),
  CONSTRAINT `fk_Contrato_Funcionario1`
    FOREIGN KEY (`funcionario`)
    REFERENCES `mydb`.`Funcionario` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `cpf` VARCHAR(15) NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `dataNascimento` DATETIME NULL,
  `email` VARCHAR(50) NULL,
  `telefone1` VARCHAR(45) GENERATED ALWAYS AS (),
  `telefone2` VARCHAR(45) NULL,
  `endereco` INT NOT NULL,
  PRIMARY KEY (`cpf`),
  INDEX `fk_Cliente_Endereco1_idx` (`endereco` ASC),
  CONSTRAINT `fk_Cliente_Endereco1`
    FOREIGN KEY (`endereco`)
    REFERENCES `mydb`.`Endereco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Fornecedor` (
  `cnpj` VARCHAR(15) NOT NULL,
  `razaoSocial` VARCHAR(50) NOT NULL,
  `descricao` VARCHAR(45) NULL,
  `email` VARCHAR(50) NULL,
  `telefone1` VARCHAR(45) GENERATED ALWAYS AS (),
  `telefone2` VARCHAR(45) NULL,
  `endereco` INT NOT NULL,
  PRIMARY KEY (`cnpj`),
  INDEX `fk_Fornecedor_Endereco_idx` (`endereco` ASC),
  CONSTRAINT `fk_Fornecedor_Endereco`
    FOREIGN KEY (`endereco`)
    REFERENCES `mydb`.`Endereco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Veiculo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `modelo` VARCHAR(45) NOT NULL,
  `ano` YEAR NOT NULL,
  `versao` VARCHAR(45) NOT NULL,
  `opcionalVidrosEletricos` TINYINT(1) NULL DEFAULT 0,
  `opcionalTravasEletricas` TINYINT(1) NULL DEFAULT 0,
  `opcionalAr` TINYINT(1) NULL DEFAULT 0,
  `opcionalFarolNeblina` TINYINT(1) NULL DEFAULT 0,
  `opcionalAltoFalantes` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Peca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Peca` (
  `id` INT NOT NULL,
  `valor` VARCHAR(45) NULL,
  `tipo` CHAR(1) NULL,
  `quantidade` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Servico` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  `valorPadrao` DECIMAL(10,2) NOT NULL,
  `valorFixo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OrcamentoServico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OrcamentoServico` (
  `id` INT NOT NULL,
  `placa` VARCHAR(45) NOT NULL,
  `data` DATE NULL,
  `Funcionario_cpf` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`, `Funcionario_cpf`),
  INDEX `fk_OrcamentoServico_Funcionario1_idx` (`Funcionario_cpf` ASC),
  CONSTRAINT `fk_OrcamentoServico_Funcionario1`
    FOREIGN KEY (`Funcionario_cpf`)
    REFERENCES `mydb`.`Funcionario` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ServicoSelecionado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ServicoSelecionado` (
  `orcamento` INT NOT NULL,
  `servico` INT NOT NULL,
  PRIMARY KEY (`orcamento`, `servico`),
  INDEX `fk_OrcamentoServico_has_Servico_Servico1_idx` (`servico` ASC),
  INDEX `fk_OrcamentoServico_has_Servico_OrcamentoServico1_idx` (`orcamento` ASC),
  CONSTRAINT `fk_OrcamentoServico_has_Servico_OrcamentoServico1`
    FOREIGN KEY (`orcamento`)
    REFERENCES `mydb`.`OrcamentoServico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OrcamentoServico_has_Servico_Servico1`
    FOREIGN KEY (`servico`)
    REFERENCES `mydb`.`Servico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`VeiculoFornecido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`VeiculoFornecido` (
  `Fornecedor_cnpj` VARCHAR(15) NOT NULL,
  `Veiculo_id` INT NOT NULL,
  PRIMARY KEY (`Fornecedor_cnpj`, `Veiculo_id`),
  INDEX `fk_Fornecedor_has_Veiculo_Veiculo1_idx` (`Veiculo_id` ASC),
  INDEX `fk_Fornecedor_has_Veiculo_Fornecedor1_idx` (`Fornecedor_cnpj` ASC),
  CONSTRAINT `fk_Fornecedor_has_Veiculo_Fornecedor1`
    FOREIGN KEY (`Fornecedor_cnpj`)
    REFERENCES `mydb`.`Fornecedor` (`cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fornecedor_has_Veiculo_Veiculo1`
    FOREIGN KEY (`Veiculo_id`)
    REFERENCES `mydb`.`Veiculo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PecaForncida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PecaForncida` (
  `fornecedor` VARCHAR(15) NOT NULL,
  `peca` INT NOT NULL,
  PRIMARY KEY (`fornecedor`, `peca`),
  INDEX `fk_Fornecedor_has_Peca_Peca1_idx` (`peca` ASC),
  INDEX `fk_Fornecedor_has_Peca_Fornecedor1_idx` (`fornecedor` ASC),
  CONSTRAINT `fk_Fornecedor_has_Peca_Fornecedor1`
    FOREIGN KEY (`fornecedor`)
    REFERENCES `mydb`.`Fornecedor` (`cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fornecedor_has_Peca_Peca1`
    FOREIGN KEY (`peca`)
    REFERENCES `mydb`.`Peca` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PecaNecessarias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PecaNecessarias` (
  `peca` INT NOT NULL,
  `orcamentoServico` INT NOT NULL,
  PRIMARY KEY (`peca`, `orcamentoServico`),
  INDEX `fk_Peca_has_OrcamentoServico_OrcamentoServico1_idx` (`orcamentoServico` ASC),
  INDEX `fk_Peca_has_OrcamentoServico_Peca1_idx` (`peca` ASC),
  CONSTRAINT `fk_Peca_has_OrcamentoServico_Peca1`
    FOREIGN KEY (`peca`)
    REFERENCES `mydb`.`Peca` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Peca_has_OrcamentoServico_OrcamentoServico1`
    FOREIGN KEY (`orcamentoServico`)
    REFERENCES `mydb`.`OrcamentoServico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OrdemServico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OrdemServico` (
  `id` INT NOT NULL,
  `tipoPagamento` CHAR(1) NULL,
  `codigoPagemento` VARCHAR(45) NULL,
  `data` VARCHAR(45) NULL,
  `valorFinal` DECIMAL(10,2) NULL,
  `desconto` DECIMAL(6,2) NULL,
  `orcamento` INT NOT NULL,
  `cliente` VARCHAR(15) NOT NULL,
  `funcionario` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`, `orcamento`, `cliente`, `funcionario`),
  INDEX `fk_OrdemServico_OrcamentoServico1_idx` (`orcamento` ASC),
  INDEX `fk_OrdemServico_Cliente1_idx` (`cliente` ASC),
  INDEX `fk_OrdemServico_Funcionario1_idx` (`funcionario` ASC),
  CONSTRAINT `fk_OrdemServico_OrcamentoServico1`
    FOREIGN KEY (`orcamento`)
    REFERENCES `mydb`.`OrcamentoServico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OrdemServico_Cliente1`
    FOREIGN KEY (`cliente`)
    REFERENCES `mydb`.`Cliente` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OrdemServico_Funcionario1`
    FOREIGN KEY (`funcionario`)
    REFERENCES `mydb`.`Funcionario` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ItemPecaServico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ItemPecaServico` (
  `peca` INT NOT NULL,
  `ordemServico` INT NOT NULL,
  `orcamento` INT NOT NULL,
  `cliente` VARCHAR(15) NOT NULL,
  `funcionario` VARCHAR(15) NOT NULL,
  `tipoPagamento` CHAR(1) NULL,
  `codigoPagamento` VARCHAR(45) NULL,
  `valorFinal` DECIMAL(10,2) NULL,
  `desconto` DECIMAL(6,2) NULL,
  `ItemPecacol` VARCHAR(45) NULL,
  `Funcionario_cpf` VARCHAR(15) NOT NULL,
  `Cliente_cpf` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`peca`, `ordemServico`, `orcamento`, `cliente`, `funcionario`, `Funcionario_cpf`, `Cliente_cpf`),
  INDEX `fk_Peca_has_OrdemServico_OrdemServico1_idx` (`ordemServico` ASC, `orcamento` ASC, `cliente` ASC, `funcionario` ASC),
  INDEX `fk_Peca_has_OrdemServico_Peca1_idx` (`peca` ASC),
  INDEX `fk_ItemPecaServico_Funcionario1_idx` (`Funcionario_cpf` ASC),
  INDEX `fk_ItemPecaServico_Cliente1_idx` (`Cliente_cpf` ASC),
  CONSTRAINT `fk_Peca_has_OrdemServico_Peca1`
    FOREIGN KEY (`peca`)
    REFERENCES `mydb`.`Peca` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Peca_has_OrdemServico_OrdemServico1`
    FOREIGN KEY (`ordemServico` , `orcamento` , `cliente` , `funcionario`)
    REFERENCES `mydb`.`OrdemServico` (`id` , `orcamento` , `cliente` , `funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ItemPecaServico_Funcionario1`
    FOREIGN KEY (`Funcionario_cpf`)
    REFERENCES `mydb`.`Funcionario` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ItemPecaServico_Cliente1`
    FOREIGN KEY (`Cliente_cpf`)
    REFERENCES `mydb`.`Cliente` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ItemVeiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ItemVeiculo` (
  `veiculo` INT NOT NULL,
  `funcionario` VARCHAR(15) NOT NULL,
  `cliente` VARCHAR(15) NOT NULL,
  `tipoPagamento` VARCHAR(45) NULL,
  `codigoPagemento` VARCHAR(45) NULL,
  `data` VARCHAR(45) NULL,
  `codigoPagamento` VARCHAR(45) NULL,
  `chasi` VARCHAR(45) NULL,
  `desconto` VARCHAR(45) NULL,
  PRIMARY KEY (`veiculo`, `funcionario`, `cliente`),
  INDEX `fk_Veiculo_has_Funcionario_Funcionario1_idx` (`funcionario` ASC),
  INDEX `fk_Veiculo_has_Funcionario_Veiculo1_idx` (`veiculo` ASC),
  INDEX `fk_ItemVeiculo_Cliente1_idx` (`cliente` ASC),
  CONSTRAINT `fk_Veiculo_has_Funcionario_Veiculo1`
    FOREIGN KEY (`veiculo`)
    REFERENCES `mydb`.`Veiculo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Veiculo_has_Funcionario_Funcionario1`
    FOREIGN KEY (`funcionario`)
    REFERENCES `mydb`.`Funcionario` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ItemVeiculo_Cliente1`
    FOREIGN KEY (`cliente`)
    REFERENCES `mydb`.`Cliente` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
